#!/bin/sh

# Run prettier and eslint on staged files
echo "(1) Running lint-staged..."
npx lint-staged

# Check if external monorepo dependencies are in sync
echo "(2) Checking external dependencies sync with syncpack..."
npx syncpack lint

# Check if dependency-cruiser rules are respected
echo "(3) Checking dependency-cruiser rules..."

echo "(3.1) Checking tsconfig.depcruise.json paths..."
node ./scripts/validate-tsconfig-paths.cjs

echo "(3.2) Running depcruise..."
npx depcruise .